# Generated by Django 3.2.5 on 2021-09-22 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.CharField(max_length=50, unique=True, verbose_name='долгота')),
                ('latitude', models.CharField(max_length=50, unique=True, verbose_name='ширина')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='preview')),
                ('text', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='телеграм id')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='телеграм никнейм')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='дата регистрации')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server_api.location', verbose_name='id координат')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='IsSubscribed',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_api.subscriber', verbose_name='id пользователя')),
                ('is_subscribed', models.BooleanField(verbose_name='статус подписки')),
            ],
            options={
                'verbose_name': 'Статус подписки',
                'verbose_name_plural': 'Статус подписки',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('locations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server_api.location', verbose_name='id координат')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
